// WORDPRESS_TOKEN is optional while the client completes plugin installation.
// Platform bindings and required secrets are generated by `npm run types`.
interface Env {
  WORDPRESS_TOKEN?: string
}
